distributionUrl=https://repo1.maven.org/maven2/io/takari/maven-wrapper/0.5.6/maven-wrapper.jar
distributionBase=repository
distributionPath=.m2/wrapper/dists
zipStoreBase=repository
zipStorePath=.m2/wrapper/dists
